### PR TITLE
Token classifier & refactor filters

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | #39

### CODE REVIEW

**Comment by rustamwin** [comment]
ℹ️  The classifier now also finds interfaces, traits and enums.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
@rustamwin https://github.com/yiisoft/classifier/pull/41#issuecomment-1772970208?

**Comment by rustamwin** [comment]
> @rustamwin https://github.com/yiisoft/classifier/pull/41#issuecomment-1772970208?

I will do it within 1-2 days.

**Comment by rustamwin** [comment]
Benchmark results here: https://github.com/yiisoft/classifier/pull/38#issuecomment-1782268810

**Pull request merged**
